app:
  env:            "local"
  environment:    "local"
  version:        "1.0.0"
  datacenterID:   1
  workerID:       1
  jaegerEndpoint: ""
  uploadPath:     ""
  visitPath:      ""
  site:           "http://127.0.0.1:8012/"
  roleModel:      ""

server:
  address:          ":8199"
  dumpRouterMap:    true
  routeOverWrite:   true
  accessLogEnabled: false
  logPath:          "manifest/logs/server"
  accessLogPattern: "access-{Ymd}.log"
  errorLogPattern:  "error-{Ymd}.log"
  openapiPath:      "/api.json"
  swaggerPath:      "/swagger"

logger:
  path:   "manifest/logs/default"
  level:  "all"
  stdout: true
  ctxKeys: [ "TraceID" ]
  admin:
    path:   "manifest/logs/admin"
    level:  "all"
    stdout: false

# 数据库连接配置
database:
  logger:
    path:   "manifest/logs/sql"
    level:  "all"
    stdout: true
    ctxKeys: [ "TraceID" ]

  default:
    default:
    link:        "mysql:root:123456@tcp(127.0.0.1:3306)/psychology_healthy"
    debug:       true
    prefix:      "sys_"
    maxIdle:     10 #连接池最大闲置的连接数
    maxOpen:     10 #连接池最大打开的连接数
    maxLifetime: 30 #(单位秒)连接对象可重复使用的时间长度

# Redis 配置示例
redis:
  default:
    address:     127.0.0.1:6379
    db:          1
    pass:        123456
    idleTimeout: 600
    maxActive:   100
  cache:
    address:     127.0.0.1:6379
    db:          1
    pass:        123456
    idleTimeout: 600

# 路由配置
router:
  # 后台
  admin:
    # 前缀
    prefix: "/api.v1/admin"
    # 不需要验证登录的路由地址
    exceptLogin: [
      "/login/captcha",         # 登录验证码
      "/login/sign",            # 登录
      "/login/logout",          # 退出
    ]
    # 不需要验证权限的路由地址
    exceptAuth: [
      "/member/info",      # 登录用户信息
      "/role/dynamic",     # 获取动态路由
    ]
  # 接口
  api:
    # 前缀
    prefix: "/api"
    # 不需要验证登录的路由地址
    exceptPath: [ ]

jwt:
  version:   "1.0"                       # 版本号
  expires:   "864000"                    # 有效期，单位：秒
  sign:      "psychology"                # 秘钥
  multiPort: true                        # 是否允许多端登录，默认为true