app:
  env:            "local"
  environment:    "local"
  version:        "1.0.0"
  datacenterID:   1
  workerID:       1
  jaegerEndpoint: ""
  uploadPath:     ""
  visitPath:      ""
  site:           "http://127.0.0.1:8012/"
  roleModel:      ""

# 路由配置
router:
  # 后台
  admin:
    # 前缀
    prefix: "/api.v1/admin"
    # 不需要验证登录的路由地址
    exceptLogin: [
      "/login/captcha",         # 登录验证码
      "/login/sign",            # 登录
      "/login/logout",          # 退出
    ]
    # 不需要验证权限的路由地址
    exceptAuth: [
      "/member/info",      # 登录用户信息
      "/role/dynamic",     # 获取动态路由
    ]
  # 接口
  api:
    # 前缀
    prefix: "/api"
    # 不需要验证登录的路由地址
    exceptPath: [ ]

jwt:
  version:   "1.0"                       # 版本号
  expires:   "864000"                    # 有效期，单位：秒
  sign:      "hotgo"                     # 秘钥
  multiPort: true                        # 是否允许多端登录，默认为true