// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Admin is the golang structure of table admin for DAO operations like Where/Data.
type Admin struct {
	g.Meta     `orm:"table:admin, do:true"`
	Id         interface{} // 主键id
	AdminNo    interface{} // 唯一标识
	Account    interface{} // 账号/手机号(默认都是手机号注册)
	Passwd     interface{} // 密码
	State      interface{} // 账号状态；200-有效;100-无效
	Salt       interface{} // 盐值
	CreateTime *gtime.Time // 创建时间
	ModifyTime *gtime.Time // 更新时间
}
