// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure of table sys_menu for DAO operations like Where/Data.
type SysMenu struct {
	g.Meta    `orm:"table:sys_menu, do:true"`
	Id        interface{} // 菜单ID
	Pid       interface{} // 父菜单ID
	Name      interface{} // 菜单名称
	Code      interface{} // 菜单编码
	Icon      interface{} // 菜单图标
	Type      interface{} // 菜单类型（M目录 C菜单 F按钮）
	Perms     interface{} // 权限标识
	Path      interface{} // 路由地址
	Component interface{} // 组件路径
	Query     interface{} // 路由参数
	IsCache   interface{} // 是否缓存：10-是，20-否
	IsVisible interface{} // 是否隐藏：10-是，20-否
	Level     interface{} // 级别
	Tree      interface{} // 树
	Sort      interface{} // 排序
	Status    interface{} // 菜单状态：10-开启，20-关闭
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
