// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysMemberRole is the golang structure of table sys_member_role for DAO operations like Where/Data.
type SysMemberRole struct {
	g.Meta   `orm:"table:sys_member_role, do:true"`
	MemberId interface{} // 用户ID
	RoleId   interface{} // 角色ID
}
