// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysMemberDao is the data access object for table sys_member.
type SysMemberDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns SysMemberColumns // columns contains all the column names of Table for convenient usage.
}

// SysMemberColumns defines and stores column names for table sys_member.
type SysMemberColumns struct {
	Id         string //
	Username   string // 帐号
	Password   string // 密码
	Type       string // 账户类型:1-普通管理员，10-超级管理员
	NickName   string // 昵称
	Avatar     string // 头像
	Sex        string // 性别:0-未知，1-男，2-女
	Email      string // 邮箱
	Birthday   string // 生日
	ProvinceId string // 省
	CityId     string // 城市
	AreaId     string // 地区
	Address    string // 默认地址
	Mobile     string // 手机号码
	VisitCount string // 访问次数
	LastAt     string // 最后登录时间
	LastIp     string // 最后一次登录ip
	Status     string // 状态:10-正常，20-关闭，30-待验证
	CreatedAt  string // 创建时间
	UpdatedAt  string // 修改时间
}

//  sysMemberColumns holds the columns for table sys_member.
var sysMemberColumns = SysMemberColumns{
	Id:         "id",
	Username:   "username",
	Password:   "password",
	Type:       "type",
	NickName:   "nick_name",
	Avatar:     "avatar",
	Sex:        "sex",
	Email:      "email",
	Birthday:   "birthday",
	ProvinceId: "province_id",
	CityId:     "city_id",
	AreaId:     "area_id",
	Address:    "address",
	Mobile:     "mobile",
	VisitCount: "visit_count",
	LastAt:     "last_at",
	LastIp:     "last_ip",
	Status:     "status",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

// NewSysMemberDao creates and returns a new DAO object for table data access.
func NewSysMemberDao() *SysMemberDao {
	return &SysMemberDao{
		group:   "default",
		table:   "sys_member",
		columns: sysMemberColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysMemberDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysMemberDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysMemberDao) Columns() SysMemberColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysMemberDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysMemberDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysMemberDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
