// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/a330202207/psychology-healthy-api/internal/model"
)

type IMember interface {
	Edit(ctx context.Context, in *model.MemberEditInput) (err error)
	UpdatePassWd(ctx context.Context, in *model.MemberUpdatePassWdInput) (err error)
	Del(ctx context.Context, in *model.MemberBaseInput) (err error)
	ResetPassWd(ctx context.Context, in *model.MemberResetPassWdInput) (err error)
	List(ctx context.Context, in *model.MemberBaseInput) (err error)
	GetInfo(ctx context.Context, in *model.MemberBaseInput) (err error)
}

var localMember IMember

func Member() IMember {
	if localMember == nil {
		panic("implement not found for interface IMember, forgot register?")
	}
	return localMember
}

func RegisterMember(i IMember) {
	localMember = i
}
