// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/a330202207/psychology-healthy-api/internal/model"
)

type IMember interface {
	Add(ctx context.Context, in *model.MemberAddInput) (out *model.MemberAddOutput, err error)
}

var localMember IMember

func Member() IMember {
	if localMember == nil {
		panic("implement not found for interface IMember, forgot register?")
	}
	return localMember
}

func RegisterMember(i IMember) {
	localMember = i
}
