// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/a330202207/psychology-healthy-api/internal/model"
)

type IMenu interface {
	Edit(ctx context.Context, in *model.MenuEditInput) (err error)
	Del(ctx context.Context, in *model.MenuBaseInput) (err error)
	Get(ctx context.Context, in *model.MenuBaseInput) (res *model.MenuGetOut, err error)
}

var localMenu IMenu

func Menu() IMenu {
	if localMenu == nil {
		panic("implement not found for interface IMenu, forgot register?")
	}
	return localMenu
}

func RegisterMenu(i IMenu) {
	localMenu = i
}
