// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/a330202207/psychology-healthy-api/internal/model"
)

type IRole interface {
	Edit(ctx context.Context, in *model.RoleEditInput) (err error)
	Del(ctx context.Context, in *model.RoleBaseInput) (err error)
	List(ctx context.Context, in *model.RoleListInput) (out *model.RoleListOut, err error)
	GetAll(ctx context.Context) (out []*model.RoleItem, err error)
}

var localRole IRole

func Role() IRole {
	if localRole == nil {
		panic("implement not found for interface IRole, forgot register?")
	}
	return localRole
}

func RegisterRole(i IRole) {
	localRole = i
}
