// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/a330202207/psychology-healthy-api/internal/dao/internal"
)

// internalSysMemberDao is internal type for wrapping internal DAO implements.
type internalSysMemberDao = *internal.SysMemberDao

// sysMemberDao is the data access object for table sys_member.
// You can define custom methods on it to extend its functionality as you wish.
type sysMemberDao struct {
	internalSysMemberDao
}

var (
	// SysMember is globally public accessible object for table sys_member operations.
	SysMember = sysMemberDao{
		internal.NewSysMemberDao(),
	}
)

// Fill with you ideas below.
