// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/a330202207/psychology-healthy-api/internal/dao/internal"
)

// internalSysMemberRoleDao is internal type for wrapping internal DAO implements.
type internalSysMemberRoleDao = *internal.SysMemberRoleDao

// sysMemberRoleDao is the data access object for table sys_member_role.
// You can define custom methods on it to extend its functionality as you wish.
type sysMemberRoleDao struct {
	internalSysMemberRoleDao
}

var (
	// SysMemberRole is globally public accessible object for table sys_member_role operations.
	SysMemberRole = sysMemberRoleDao{
		internal.NewSysMemberRoleDao(),
	}
)

// Fill with you ideas below.
