// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Admin is the golang structure for table admin.
type Admin struct {
	Id         uint        `json:"id"         description:"主键id"`
	AdminNo    uint64      `json:"adminNo"    description:"唯一标识"`
	Account    string      `json:"account"    description:"账号/手机号(默认都是手机号注册)"`
	Passwd     string      `json:"passwd"     description:"密码"`
	State      int         `json:"state"      description:"账号状态；200-有效;100-无效"`
	Salt       string      `json:"salt"       description:"盐值"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	ModifyTime *gtime.Time `json:"modifyTime" description:"更新时间"`
}
