// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysRoleMenu is the golang structure for table sys_role_menu.
type SysRoleMenu struct {
	RoleId uint64 `json:"roleId" description:"角色ID"`
	MenuId uint64 `json:"menuId" description:"菜单ID"`
}
