// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysMemberRole is the golang structure for table sys_member_role.
type SysMemberRole struct {
	MemberId int64  `json:"memberId" description:"用户ID"`
	RoleId   uint64 `json:"roleId"   description:"角色ID"`
}
