// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysRole is the golang structure for table sys_role.
type SysRole struct {
	Id        int64       `json:"id"        description:"角色ID"`
	Name      string      `json:"name"      description:"角色名称"`
	Key       string      `json:"key"       description:"角色权限字符串"`
	Sort      uint        `json:"sort"      description:"排序"`
	Status    uint        `json:"status"    description:"角色状态：10-开启，20-关闭"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
}
