// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure for table sys_menu.
type SysMenu struct {
	Id        int64       `json:"id"        description:"菜单ID"`
	Pid       uint64      `json:"pid"       description:"父菜单ID"`
	Name      string      `json:"name"      description:"菜单名称"`
	Code      string      `json:"code"      description:"菜单编码"`
	Icon      string      `json:"icon"      description:"菜单图标"`
	Type      string      `json:"type"      description:"菜单类型（M目录 C菜单 F按钮）"`
	Perms     string      `json:"perms"     description:"权限标识"`
	Path      string      `json:"path"      description:"路由地址"`
	Component string      `json:"component" description:"组件路径"`
	Query     string      `json:"query"     description:"路由参数"`
	IsCache   uint        `json:"isCache"   description:"是否缓存：10-是，20-否"`
	IsVisible uint        `json:"isVisible" description:"是否隐藏：10-是，20-否"`
	Level     uint        `json:"level"     description:"级别"`
	Tree      string      `json:"tree"      description:"树"`
	Sort      uint        `json:"sort"      description:"排序"`
	Status    uint        `json:"status"    description:"菜单状态：10-开启，20-关闭"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
}
