// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysConfig is the golang structure for table sys_config.
type SysConfig struct {
	Id        int64       `json:"id"        description:"配置ID"`
	Name      string      `json:"name"      description:"参数名称"`
	Key       string      `json:"key"       description:"参数键名"`
	Value     string      `json:"value"     description:"参数键值"`
	Status    int         `json:"status"    description:"状态：10-开启，20-关闭"`
	Remark    string      `json:"remark"    description:"备注"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
}
